=== paohaijiao/jquick-mybatis/src/main/resources/paohaijiao/dtd/Jquick-mybatis.dtd
<?xml version="1.0" encoding="UTF-8"?>
  <!ELEMENT mapper (sql*, insert*, delete*, update*, select*)>
     <!ATTLIST mapper
                namespace CDATA #REQUIRED
     >

    <!ELEMENT sql (#PCDATA)>
    <!ATTLIST sql
                name CDATA #REQUIRED
    >
    <!ELEMENT insert (#PCDATA | if* | foreach*)*>
     <!ATTLIST insert
                name CDATA #REQUIRED
                paramClass CDATA #IMPLIED
                returnClass CDATA #IMPLIED
                >

     <!ELEMENT delete (#PCDATA | if* | foreach*)*>
     <!ATTLIST delete
                name CDATA #REQUIRED
                paramClass CDATA #IMPLIED
                >

     <!ELEMENT update (#PCDATA | if*)*>
     <!ATTLIST update
                name CDATA #REQUIRED
                paramClass CDATA #IMPLIED
                >

     <!ELEMENT select (#PCDATA | include* | if* | foreach*)*>
     <!ATTLIST select
                name CDATA #REQUIRED
                paramClass CDATA #IMPLIED
                returnClass CDATA #IMPLIED
                >

     <!ELEMENT if (#PCDATA | if*)*>
     <!ATTLIST if
                test CDATA #REQUIRED
                >

     <!ELEMENT foreach (#PCDATA)*>
     <!ATTLIST foreach
                collection CDATA #REQUIRED
                item CDATA #REQUIRED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                separator CDATA #IMPLIED
                >

     <!ELEMENT include EMPTY>
     <!ATTLIST include
                refid CDATA #REQUIRED
                >

=== paohaijiao/jquick-mybatis/src/main/resources/my.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//JQUICK//DTD MYBATIS MAPPER 1.0//EN"
        "classpath:paohaijiao/dtd/Jquick-mybatis.dtd">
<mapper namespace="com.example.mapper.UserMapper">
    <sql name="Base_Column_List">
        id, username, password, age, email, status
    </sql>
    <insert name="insertUser" paramClass="com.example.entity.User" returnClass="">
    INSERT INTO user
    <if test="username != null">username,</if>
    <if test="password != null">password,</if>
    <if test="age != null">age,</if>
    <if test="email != null">email,</if>
    <if test="status != null">status,</if>

    <if test="username != null">#{username},</if>
    <if test="password != null">#{password},</if>
    <if test="age != null">#{age},</if>
    <if test="email != null">#{email},</if>
    <if test="status != null">#{status},</if>
</insert>

<insert name="batchInsertUser">
INSERT INTO user (username, password, age, email, status)
VALUES
<foreach collection="list" item="item" separator=",">
    (#{item.username}, #{item.password}, #{item.age}, #{item.email}, #{item.status})
</foreach>
</insert>

<delete name="deleteUserById" paramClass="java.lang.Long">
DELETE FROM user WHERE id = #{id}
</delete>

<delete name="batchDeleteUser">
DELETE FROM user WHERE id IN
<foreach collection="ids" item="id" open="(" separator="," close=")">
    #{id}
</foreach>
</delete>

<update name="updateUser" paramClass="com.example.entity.User">
    UPDATE user
    set
    <if test="username != null">username = #{username},</if>
    <if test="password != null">password = #{password},</if>
    <if test="age != null">age = #{age},</if>
    <if test="email != null">email = #{email},</if>
    <if test="status != null">status = #{status},</if>
    WHERE id = #{id}
</update>

<select name="getUserById" returnClass="">
    SELECT <include refid="Base_Column_List"/> FROM user WHERE id = #{id}
</select>

<select name="findUserList" paramClass="com.example.entity.User" returnClass="">
SELECT <include refid="Base_Column_List"/> FROM user
where
<if test="username != null and username != ''">
    AND username LIKE CONCAT('%', #{username}, '%')
</if>
<if test="age != null">
    AND age = #{age}
</if>
<if test="email != null and email != ''">
    AND email = #{email}
</if>
<if test="status != null">
    AND status = #{status}
</if>
ORDER BY id DESC
</select>

<select name="getUserByIds" returnClass="BaseResultMap">
SELECT <include refid="Base_Column_List"/> FROM user WHERE id IN
<foreach collection="ids" item="id" open="(" separator="," close=")">
    #{id}
</foreach>
</select>
</mapper>

=== paohaijiao/jquick-mybatis/src/test/resources/mybatis.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//JQUICK//DTD MYBATIS MAPPER 1.0//EN"
        "classpath:paohaijiao/dtd/Jquick-mybatis.dtd">
<mapper namespace="com.example.mapper.UserMapper">
    <insert name="insertUser" paramClass="com.github.paohaijiao.model.User">
        INSERT INTO test.t_user (
            <if test="user.id != null">id,</if>
            <if test="user.username != null">username,</if>
            <if test="user.password != null">password,</if>
            <if test="user.age != null">age,</if>
            <if test="user.email != null">email,</if>
            <if test="user.status != null">status,</if>
            <if test="user.createTime != null">create_time</if>
        ) VALUES (
            <if test="user.id != null">#{user.id},</if>
            <if test="user.username != null">'#{user.username}',</if>
            <if test="user.password != null">'#{user.password}',</if>
            <if test="user.age != null">#{user.age},</if>
            <if test="user.email != null">'#{user.email}',</if>
            <if test="user.status != null">#{user.status},</if>
            <if test="user.createTime != null">'#{user.createTime}'</if>
        )
    </insert>

<insert name="batchInsertUser">
        INSERT INTO test.t_user (id,username, password, age, email, status)
        VALUES
        <foreach collection="list" item="item" separator=",">
            (#{item.id}, '#{item.username}', '#{item.password}', #{item.age},' #{item.email}', #{item.status})
        </foreach>
</insert>

<delete name="deleteUserById" paramClass="java.lang.Long">
        DELETE FROM test.t_user WHERE id = #{id}
</delete>

<delete name="batchDeleteUser">
        DELETE FROM test.t_user WHERE id IN
        <foreach collection="ids" item="id" open="(" separator="," close=")">
            #{id}
        </foreach>
</delete>

<update name="updateUser" paramClass="com.github.paohaijiao.model.User">
    UPDATE test.t_user
        set id = #{user.id}
        <if test="user.username != null">,username = '#{user.username}'</if>
        <if test="user.password != null">,password = '#{user.password}'</if>
        <if test="user.age != null">,age = #{user.age}</if>
        <if test="user.email != null">,email = '#{user.email}'</if>
        <if test="user.status != null">,status = #{user.status}</if>
    WHERE id = #{user.id}
</update>

<select name="getUserById" returnClass="com.github.paohaijiao.model.User">
    SELECT * FROM test.t_user WHERE id = #{id}
</select>
<select name="getUserDetailById" returnClass="java.util.Map">
    SELECT * FROM test.t_user WHERE id = #{id}
</select>




<select name="findUserList" paramClass="com.github.paohaijiao.model.User" returnClass="java.util.List">
        SELECT * FROM test.t_user
            where true
            <if test="username != null and username != ''">
                AND username LIKE CONCAT('%', #{username}, '%')
            </if>
            <if test="age != null">
                AND age = #{age}
            </if>
            <if test="email != null and email != ''">
                AND email = #{email}
            </if>
            <if test="status != null">
                AND status = #{status}
            </if>
        ORDER BY id DESC
</select>
    <select name="findUserMapList" paramClass="com.github.paohaijiao.model.User" returnClass="java.util.List">
        SELECT * FROM test.t_user
        where true
        <if test="user.username != null and user.username != ''">
            AND username LIKE '%#{user.username}%'
        </if>
        <if test="user.age != null">
            AND age = #{user.age}
        </if>
        <if test="user.email != null and user.email != ''">
            AND email = #{user.email}
        </if>
        <if test="user.status != null">
            AND status = #{user.status}
        </if>
        ORDER BY id DESC
    </select>

    <select name="getUserByIds" returnClass="java.util.List">
            SELECT * FROM test.t_user WHERE id IN
            <foreach collection="ids" item="id" open="(" separator="," close=")">
                #{id}
            </foreach>
    </select>
    <select name="getUserByUserNames" returnClass="java.util.List">
        SELECT * FROM test.t_user WHERE username IN
        <foreach collection="users" item="user" open="(" separator="," close=")">
            '#{user.username}'
        </foreach>
    </select>
    <select name="getUserByUserNamesAndValue" returnClass="java.util.List">
        SELECT * FROM test.t_user WHERE username IN
        <foreach collection="users" item="user" open="(" separator="," close=")">
            <if test="user.username != null and user.username != ''">
                AND username LIKE '%#{user.username}%'
            </if>
        </foreach>
    </select>





</mapper>
